import styled from 'styled-components';
import { device, PanelBordered } from '../layout/LayoutStyles';

export const LoaderPage = styled.div`
  align-items: center;
  background-color: ${(props) => props.theme.main};
  display: flex;
  justify-content: center;
  height: ${({ theme }) => theme.currSiteSize.height}px;
  width: ${({ theme }) => theme.currSiteSize.width}px;
`;

export const LoaderContainer = styled(PanelBordered)`
  display: flex;
  flex-direction: column;
  gap: 40px;
  padding: 2rem;
  width: 90%;
  @media screen and (${device.mobileL}) {
    padding: 5rem 10rem;
    width: auto;
  }
`;

export const LoaderSpinner = styled.div`
  animation: spinner 1s linear infinite;
  width: ${(props) => props.width || '6rem'};
  height: ${(props) => props.height || '6rem'};
  border-radius: 50%;
  box-shadow: 0 4px 0 0 ${(props) => props.color || '#42427d'};
  transform-origin: center;

  @keyframes spinner {
    0% {
      transform: rotate(0deg);
    }
    50% {
      transform: rotate(180deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
`;

// .ldio-v6sfsysqkk div {
//   position: absolute;
//   animation: ldio-v6sfsysqkk 1s linear infinite;
//   width: 160px;
//   height: 160px;
//   top: 20px;
//   left: 20px;
//   border-radius: 50%;
//   box-shadow: 0 4px 0 0 #42427d;
//   transform-origin: 80px 82px;
// }
// .loadingio-spinner-eclipse-noojs3jgon {
//   width: 200px;
//   height: 200px;
//   display: inline-block;
//   overflow: hidden;
//   background: #ffffff;
// }
// .ldio-v6sfsysqkk {
//   width: 100%;
//   height: 100%;
//   position: relative;
//   transform: translateZ(0) scale(1);
//   backface-visibility: hidden;
//   transform-origin: 0 0; /* see note above */
// }
// .ldio-v6sfsysqkk div { box-sizing: content-box; }
// /* generated by https://loading.io/ */
// </style>
